### ISSUE TITLE
Mackbook Pro Iris Built-in GPU OpenGL Error 1280

### ISSUE THREAD

**Issue by max-uho** [diwi/LiquidFunProcessing#2] opened 2017-07-12 10:59 UTC
Hi Diwi,
I was trying to use your fantastic library, but my computer is throwing an error:

**OpenGL error 1280 at top endDraw(): invalid enumerant**

While playing around with the examples, only the debug view is available.
Very much looking forward to reading you on this issue,
Max

PS: I have very little hope that that can be solved on your side, just thought maybe you'd add a compatible chipset list in readme file.

**Comment by diwi** [comment] 2017-07-12 15:08
Hi, thanks for filing this issue.

Indeed i cant reproduce this error on my system.
On what examples do you get this error-message? is it only happening when particles are involved?

I uploaded a new release v1.02 (5) with better error-feedback.

In case the error happens in the particle-demos:
This release also comes with a new example (https://github.com/diwi/LiquidFunProcessing/tree/master/examples/liquidfun_DamBreak_PShapeParticles) where particles are rendered as PShapes instead of OpenGL points. 
This should help to locate the source of this error, i hope.

**Comment by max-uho** [comment] 2017-07-14 13:51
Thanks a lot for the fast reply (excuse my slow response time).
The error did disappear on the PShape demo.
LiquidFun_DamBreak_LiquidFx now throws:

**OpenGL error 1280 at DwParticleRenderGL.display-pointRendering: invalid enumerant**

I did research the issue a bit on Google, and it seems this error (1280) is sometimes solved by updating the graphics card's driver. Obviously, on Mac OS, this comes bundled with the general OS updates (everything up to date over here). Not much we can do about that apart from waiting for apple to update their drivers. I'll check if the issue can be solved on Windows when I next reboot into bootcamp.

Side Note:
With your other library PixelFlow, the Fluid_CustomParticles example also throws an error on my system, hope that helps locate something

**ParticelSystem.render | GL_ERROR: invalid enumerant**

**Comment by diwi** [comment] 2017-07-14 16:45
this narrows the errors down to these 3 lines:

https://github.com/diwi/LiquidFunProcessing/blob/master/src/com/thomasdiewald/liquidfun/java/render/DwParticleRenderGL.java#L249

in the latest release, i tried to works around this, so hopefully the point sprites are rendered now correctly.

The error in the pixelflow library seems to be the exact same problem, thanks for the hint!
https://github.com/diwi/PixelFlow/blob/master/src/com/thomasdiewald/pixelflow/java/dwgl/DwGLSLProgram.java#L307

**Comment by diwi** [comment] 2017-09-26 19:52
should be fixed now in release: LiquidFunProcessing v1.04 (7)

**Closed as completed by diwi** 2017-09-26 19:52 UTC
